[book]
title="OvenInjector"
authors=["hayasaka3218"]
description="A mod loader for Pizza Tower."
src="src"
language="en"

[output.html]
additional-css=["theme/whichlang.css"]
additional-js=["theme/whichlang.js"]