[book]
title="OvenInjector"
authors=["hayasaka3218"]
description="A mod loader for Pizza Tower."
src="src"
language="en"

[output.html]
additional-js=["theme/h.js.gml.js"]

[output.html.fold]
enable=false
level=1

[output.html.playground]
editable=true

[output.html.print]
enable=false
